### PR TITLE
Fixing CI issues

### PR DESCRIPTION
**Pull request by sean-parent**
Creating PR to test CI fix.

### CODE REVIEW

**Comment by dabrahams** [comment]
I won't kibitz further after this but it looks like you might be trying to do too many things at once and the scope of the PR is too large. The things that should eventually be pruned aren't causing the failures in the main branch, but removing them _can_ cause failures.  I would start by just getting the tests to pass, and do that in one PR, then prune in followup PRs.  If you're confident this is going to work out, feel free to ignore me of course.

**Comment by sean-parent** [comment]
One of the Windows builds was failing to compile libfmt, and the only catch2 test was failing on some platforms (hypothesis was that it may be a problem with throwing across a dll boundary since those tests also build catch2 as a dll). So simplifying. I've made some progress but a bit stuck. One thing I'm seeing locally is an interaction with  `WILL_FAIL YES` and `PASS_REGULAR_EXPRESSION` on the abort tests. I tried `_Exit(EXIT_SUCCESS)` in the handler but that still counts as a failure.

**Comment by dabrahams** [comment]
> hypothesis was that it may be a problem with throwing across a dll boundary since those tests also build catch2 as a dll

Don't we want to make everything work if you throw across a dll boundary?

> One thing I'm seeing locally is an interaction with `WILL_FAIL YES` and `PASS_REGULAR_EXPRESSION` on the abort tests. 

That interaction, from my experiments, is that `WILL_FAIL YES` inverts the sense of `PASS_` and `FAIL_`.  Thus [this code](https://github.com/stlab/adobe-contract-checks/blob/eb3c7b7cb65f1e0eb2d99dc9eaeef498952533a8/test/CMakeLists.txt#L48-L51).  Note that the `PASS_REGULAR_EXPRESSION` is the _un_-expected pattern.

**Comment by dabrahams** [comment]
Closing as obsolete. @sean-parent feel free to reopen.

**Pull request closed without merging**
